reviewer.py: add exception handling for empty json file
Sometimes the json file might be empty, catch the exception so that
it won't crash like:
Traceback (most recent call last):
  File "./reviewer.py", line 88, in <module>
    report = json.load(urllib.request.urlopen(url))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>